pipeline {
  agent {
            docker { image 'maven:3.8.1-adoptopenjdk-11' }
  }
  stages {
    stage('Compile-Run') {
      steps {
        sh 'javac HelloWorld.java'
        sh 'java HelloWorld.java'
      }
    }
  }
}
